// <auto-generated />
namespace Infrastructure.Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _6_18_2018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_6_18_2018));
        
        string IMigrationMetadata.Id
        {
            get { return "201806181209388_6_18_2018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
