// <auto-generated />
namespace Infrastructure.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _5_23_2018_phase1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_5_23_2018_phase1));
        
        string IMigrationMetadata.Id
        {
            get { return "201805230928537_5_23_2018_phase1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
